// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: api/v1/fields/fields.proto

package fields

import (
	model "github.com/VeneLooool/fields-api/internal/pb/api/v1/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateField) Reset() {
	*x = CreateField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateField) ProtoMessage() {}

func (x *CreateField) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateField.ProtoReflect.Descriptor instead.
func (*CreateField) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{0}
}

type UpdateField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateField) Reset() {
	*x = UpdateField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateField) ProtoMessage() {}

func (x *UpdateField) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateField.ProtoReflect.Descriptor instead.
func (*UpdateField) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{1}
}

type GetFieldByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFieldByID) Reset() {
	*x = GetFieldByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldByID) ProtoMessage() {}

func (x *GetFieldByID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldByID.ProtoReflect.Descriptor instead.
func (*GetFieldByID) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{2}
}

type DeleteField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteField) Reset() {
	*x = DeleteField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteField) ProtoMessage() {}

func (x *DeleteField) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteField.ProtoReflect.Descriptor instead.
func (*DeleteField) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{3}
}

type CreateField_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Culture string `protobuf:"bytes,2,opt,name=culture,proto3" json:"culture,omitempty"`
}

func (x *CreateField_Request) Reset() {
	*x = CreateField_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateField_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateField_Request) ProtoMessage() {}

func (x *CreateField_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateField_Request.ProtoReflect.Descriptor instead.
func (*CreateField_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateField_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateField_Request) GetCulture() string {
	if x != nil {
		return x.Culture
	}
	return ""
}

type CreateField_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field *model.Field `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *CreateField_Response) Reset() {
	*x = CreateField_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateField_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateField_Response) ProtoMessage() {}

func (x *CreateField_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateField_Response.ProtoReflect.Descriptor instead.
func (*CreateField_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateField_Response) GetField() *model.Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type UpdateField_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Culture string `protobuf:"bytes,3,opt,name=culture,proto3" json:"culture,omitempty"`
}

func (x *UpdateField_Request) Reset() {
	*x = UpdateField_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateField_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateField_Request) ProtoMessage() {}

func (x *UpdateField_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateField_Request.ProtoReflect.Descriptor instead.
func (*UpdateField_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateField_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateField_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateField_Request) GetCulture() string {
	if x != nil {
		return x.Culture
	}
	return ""
}

type UpdateField_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field *model.Field `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *UpdateField_Response) Reset() {
	*x = UpdateField_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateField_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateField_Response) ProtoMessage() {}

func (x *UpdateField_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateField_Response.ProtoReflect.Descriptor instead.
func (*UpdateField_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UpdateField_Response) GetField() *model.Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type GetFieldByID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFieldByID_Request) Reset() {
	*x = GetFieldByID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldByID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldByID_Request) ProtoMessage() {}

func (x *GetFieldByID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldByID_Request.ProtoReflect.Descriptor instead.
func (*GetFieldByID_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetFieldByID_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFieldByID_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field *model.Field `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *GetFieldByID_Response) Reset() {
	*x = GetFieldByID_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldByID_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldByID_Response) ProtoMessage() {}

func (x *GetFieldByID_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldByID_Response.ProtoReflect.Descriptor instead.
func (*GetFieldByID_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetFieldByID_Response) GetField() *model.Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type DeleteField_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteField_Request) Reset() {
	*x = DeleteField_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_fields_fields_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteField_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteField_Request) ProtoMessage() {}

func (x *DeleteField_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_fields_fields_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteField_Request.ProtoReflect.Descriptor instead.
func (*DeleteField_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_fields_fields_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DeleteField_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_v1_fields_fields_proto protoreflect.FileDescriptor

var file_api_v1_fields_fields_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x37, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75,
	0x6c, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x47, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x6c, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65,
	0x1a, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0x6b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x79,
	0x49, 0x44, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x40, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0x28, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x19,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0x93, 0x04, 0x0a, 0x06, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x83, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x2d, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x3a, 0x01, 0x2a, 0x22, 0x0a,
	0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x88, 0x01, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2d, 0x2e, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x3a, 0x01, 0x2a, 0x1a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x88, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x42, 0x79, 0x49, 0x44, 0x12, 0x2e, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x79, 0x49, 0x44, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x79, 0x49, 0x44, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12,
	0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x12, 0x6d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x2d, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a, 0x0f,
	0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x65,
	0x6e, 0x65, 0x4c, 0x6f, 0x6f, 0x6f, 0x6f, 0x6c, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x3b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_fields_fields_proto_rawDescOnce sync.Once
	file_api_v1_fields_fields_proto_rawDescData = file_api_v1_fields_fields_proto_rawDesc
)

func file_api_v1_fields_fields_proto_rawDescGZIP() []byte {
	file_api_v1_fields_fields_proto_rawDescOnce.Do(func() {
		file_api_v1_fields_fields_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_fields_fields_proto_rawDescData)
	})
	return file_api_v1_fields_fields_proto_rawDescData
}

var file_api_v1_fields_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_fields_fields_proto_goTypes = []any{
	(*CreateField)(nil),           // 0: fields_api.api.v1.fields.CreateField
	(*UpdateField)(nil),           // 1: fields_api.api.v1.fields.UpdateField
	(*GetFieldByID)(nil),          // 2: fields_api.api.v1.fields.GetFieldByID
	(*DeleteField)(nil),           // 3: fields_api.api.v1.fields.DeleteField
	(*CreateField_Request)(nil),   // 4: fields_api.api.v1.fields.CreateField.Request
	(*CreateField_Response)(nil),  // 5: fields_api.api.v1.fields.CreateField.Response
	(*UpdateField_Request)(nil),   // 6: fields_api.api.v1.fields.UpdateField.Request
	(*UpdateField_Response)(nil),  // 7: fields_api.api.v1.fields.UpdateField.Response
	(*GetFieldByID_Request)(nil),  // 8: fields_api.api.v1.fields.GetFieldByID.Request
	(*GetFieldByID_Response)(nil), // 9: fields_api.api.v1.fields.GetFieldByID.Response
	(*DeleteField_Request)(nil),   // 10: fields_api.api.v1.fields.DeleteField.Request
	(*model.Field)(nil),           // 11: fields_api.api.v1.model.Field
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_api_v1_fields_fields_proto_depIdxs = []int32{
	11, // 0: fields_api.api.v1.fields.CreateField.Response.field:type_name -> fields_api.api.v1.model.Field
	11, // 1: fields_api.api.v1.fields.UpdateField.Response.field:type_name -> fields_api.api.v1.model.Field
	11, // 2: fields_api.api.v1.fields.GetFieldByID.Response.field:type_name -> fields_api.api.v1.model.Field
	4,  // 3: fields_api.api.v1.fields.Fields.CreateField:input_type -> fields_api.api.v1.fields.CreateField.Request
	6,  // 4: fields_api.api.v1.fields.Fields.UpdateField:input_type -> fields_api.api.v1.fields.UpdateField.Request
	8,  // 5: fields_api.api.v1.fields.Fields.GetFieldByID:input_type -> fields_api.api.v1.fields.GetFieldByID.Request
	10, // 6: fields_api.api.v1.fields.Fields.DeleteField:input_type -> fields_api.api.v1.fields.DeleteField.Request
	5,  // 7: fields_api.api.v1.fields.Fields.CreateField:output_type -> fields_api.api.v1.fields.CreateField.Response
	7,  // 8: fields_api.api.v1.fields.Fields.UpdateField:output_type -> fields_api.api.v1.fields.UpdateField.Response
	9,  // 9: fields_api.api.v1.fields.Fields.GetFieldByID:output_type -> fields_api.api.v1.fields.GetFieldByID.Response
	12, // 10: fields_api.api.v1.fields.Fields.DeleteField:output_type -> google.protobuf.Empty
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_fields_fields_proto_init() }
func file_api_v1_fields_fields_proto_init() {
	if File_api_v1_fields_fields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_fields_fields_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetFieldByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateField_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateField_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateField_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateField_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetFieldByID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetFieldByID_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_fields_fields_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteField_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_fields_fields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_fields_fields_proto_goTypes,
		DependencyIndexes: file_api_v1_fields_fields_proto_depIdxs,
		MessageInfos:      file_api_v1_fields_fields_proto_msgTypes,
	}.Build()
	File_api_v1_fields_fields_proto = out.File
	file_api_v1_fields_fields_proto_rawDesc = nil
	file_api_v1_fields_fields_proto_goTypes = nil
	file_api_v1_fields_fields_proto_depIdxs = nil
}
